[supervisor]
id = "0679be07-6106-48aa-8057-b1d4f2e18a99"
type = "nbd_netboot"

[nbd_netboot_host]
model = "Raspberry Pi 5 8GB"
serial_no = ""

[nbd_netboot_console]
udev_filters = [
  'ENV{ID_MODEL}=="Debug_Probe__CMSIS-DAP_"',
  'ENV{ID_USB_SERIAL_SHORT}=="E6633861A3918138"',
]
baudrate = 115200

[board]
manufacturer = "nordic_semiconductor"
model = "nrf52840dk"
hwrev = ""
serial_no = ""
