[supervisor]
id = "8ff22e8e-ead7-433a-a921-c7206face09d"
type = "nbd_netboot"

[nbd_netboot_host]
model = "Raspberry Pi 5 8GB"
serial_no = ""

[nbd_netboot_console]
udev_filters = [
  'ENV{ID_MODEL}=="Debug_Probe__CMSIS-DAP_"',
  'ENV{ID_USB_SERIAL_SHORT}=="E6633861A3376438"',
]
baudrate = 115200

[board]
manufacturer = "Nordic Semiconductor"
model = "nRF52840DK"
hwrev = ""
serial_no = ""
